export { HOME, NOT_FOUND } from '@shared/router/names'

export const ARRANGEMENT_DETAILS = 'arrangement-details'
export const ARRANGEMENT_FORM_LOCAL = 'arrangement-form-local'
export const ARRANGEMENT_FORM_REMOTE = 'arrangement-form-remote'
export const ARRANGEMENT_OVERVIEW = 'arrangement-overview'
export const LOGIN_CALLBACK_VIEW = 'login-callback'
export const MY_DETAILS_EDIT = 'my-details-edit'
export const MY_DETAILS_OVERVIEW = 'my-details-overview'
export const MY_MESSAGE_DETAILS = 'my-message-details'
export const MY_MESSAGES_OVERVIEW = 'my-messages-overview'
export const MY_MESSAGES_PAGE = 'my-messages-overview-page'
export const MY_REQUEST_DETAILS = 'my-request-details'
export const MY_REQUEST_EDIT = 'my-request-edit'
export const MY_REQUEST_STATUS = 'my-request-status'
export const MY_REQUESTS_OVERVIEW = 'my-requests-overview'
