export enum InputType {
  BUTTON = 'button',
  CHECKBOX_GROUP = 'checkbox-group',
  CHECKBOX = 'checkbox',
  COLOR = 'color',
  DATE = 'date',
  DATETIME_LOCAL = 'datetime-local',
  EMAIL = 'email',
  FILE = 'file',
  HIDDEN = 'hidden',
  IMAGE = 'image',
  INTEGER = 'integer',
  MONTH = 'month',
  NUMBER = 'number',
  PASSWORD = 'password',
  RADIO = 'radio',
  RANGE = 'range',
  RESET = 'reset',
  SEARCH = 'search',
  SUBMIT = 'submit',
  TEL = 'tel',
  TEXT = 'text',
  TEXTAREA = 'textarea',
  TIME = 'time',
  URL = 'url',
  WEEK = 'week',
  SELECT = 'select'
}
