export { HOME, NOT_FOUND } from '@shared/router/names'

export const ALL_CASES_OVERVIEW = 'all-cases-overview'
export const CHECK_DETAILS = 'check-details'
export const CHECKS_OVERVIEW = 'checks-overview'
export const FORGOT_PASSWORD = 'forgot-password'
export const IBAN_CHECK = 'iban-check'
export const LOGIN = 'login'
export const LOGIN_VIEW = 'login-view'
export const MY_CASE_DETAILS = 'my-case-details'
export const MY_CASE_DETAILS_HISTORY = 'my-case-details-history'
export const MY_CASE_DETAILS_REVIEWER = 'my-case-details-reviewer'
export const MY_CASES_OVERVIEW = 'my-cases-overview'
export const PASSWORD_UPDATE_VIEW = 'password-update-view'
export const PASSWORD_RESET_VIEW = 'password-reset'
export const PREVIEW_CASE_SUBMIT = 'preview-case-submit'
export const PROFILE_VIEW = 'profile-view'
export const REFRESH = 'refresh'
export const REPORT_DETAILS = 'report-details'
export const REPORTS_OVERVIEW = 'reports-overview'
export const REVIEW_CASE = 'review-case'
export const TWO_FACTOR_VIEW = 'two-factor-view'
