name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-type-check:
    name: Lint and type checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript Type Check
        run: npm run type-check

  build-projects:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - name: Build portal
        run: npm run build:portal

      - name: Build assessment
        run: npm run build:assessment

  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Run SonarCloud scanner
          uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/sonarcloud@main
          with:
            sonar-token: ${{ secrets.SONAR_TOKEN }}
