name: Lint documentation
on:
  pull_request:
    paths:
      - '**.md'
jobs:
  mdlint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        fix: true
        globs: '**/*.md'

# https://github.com/DavidAnson/markdownlint
